FROM python:3.8-slim-buster

RUN apt-get update && \
    apt-get install -y default-jdk && \
    apt-get install -y ant && \
    apt-get clean;

#Create non-root user
RUN useradd -ms /bin/bash python-api
USER python-api

WORKDIR /app

COPY . /app
 
RUN pip install -r requirements.txt

EXPOSE 8080

ENV NAME World

CMD ["python", "Assignment/assignmentfile.py"]