FROM python:3.8-slim-buster
LABEL allison

#Create non-root user
RUN useradd -ms /bin/bash python-api
USER python-api

#Copy the source files into the container
WORKDIR /repo
COPY . /repo

#Install pip requirments
RUN python -m pip install -r requirementsfile.txt
RUN pip install --upgrade pip && \
    pip install -r requirementsfile.txt 
RUN assignmentfile.py

#Install the AWS CLI and clean up files?

#Define the command to be run when the container is started
EXPOSE 8080
ENTRYPOINT ["python3"]
CMD ["ETL-project-allison.py"]

#Build docker image using dockerfile
docker image build -t dockerimage